import type { BloodGroup, Patient, PatientStatus } from "./types";

export const patientsData: Patient[] = [
  {
    id: "PAT-001",
    patientId: "P-2024-0001",
    name: "Emily Johnson",
    initials: "EJ",
    avatar: "",
    age: 34,
    gender: "Female",
    bloodGroup: "A+",
    email: "emily.johnson@email.com",
    phone: "+1 (555) 0101",
    department: "Cardiology",
    assignedDoctor: "Dr. Sarah Johnson",
    assignedDoctorInitials: "SJ",
    lastVisit: "2025-12-15",
    upcomingAppointment: "2026-01-20",
    status: "Active",
    insurance: "Blue Cross",
    registrationDate: "2024-03-10",
    address: "123 Main St, New York, NY 10001",
    emergencyContact: "+1 (555) 0901",
    notes: "Patient has a history of hypertension. Regular check-ups required.",
  },
  {
    id: "PAT-002",
    patientId: "P-2024-0002",
    name: "James Wilson",
    initials: "JW",
    avatar: "",
    age: 58,
    gender: "Male",
    bloodGroup: "O-",
    email: "james.wilson@email.com",
    phone: "+1 (555) 0102",
    department: "Neurology",
    assignedDoctor: "Dr. James Mitchell",
    assignedDoctorInitials: "JM",
    lastVisit: "2026-01-05",
    upcomingAppointment: "2026-02-01",
    status: "Active",
    insurance: "Aetna",
    registrationDate: "2024-01-15",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    emergencyContact: "+1 (555) 0902",
    notes: "Migraine patient. Responds well to prescribed medication.",
  },
  {
    id: "PAT-003",
    patientId: "P-2024-0003",
    name: "Sophia Martinez",
    initials: "SM",
    avatar: "",
    age: 7,
    gender: "Female",
    bloodGroup: "B+",
    email: "sophia.martinez@email.com",
    phone: "+1 (555) 0103",
    department: "Pediatrics",
    assignedDoctor: "Dr. Lisa Park",
    assignedDoctorInitials: "LP",
    lastVisit: "2026-01-10",
    upcomingAppointment: "2026-01-25",
    status: "Active",
    insurance: "Cigna",
    registrationDate: "2024-06-20",
    address: "789 Pine Rd, Chicago, IL 60601",
    emergencyContact: "+1 (555) 0903",
    notes: "Routine pediatric care. Vaccinations up to date.",
  },
  {
    id: "PAT-004",
    patientId: "P-2024-0004",
    name: "Robert Chen",
    initials: "RC",
    avatar: "",
    age: 45,
    gender: "Male",
    bloodGroup: "AB+",
    email: "robert.chen@email.com",
    phone: "+1 (555) 0104",
    department: "Orthopedics",
    assignedDoctor: "Dr. David Kim",
    assignedDoctorInitials: "DK",
    lastVisit: "2025-12-28",
    upcomingAppointment: null,
    status: "Discharged",
    insurance: "United Health",
    registrationDate: "2024-02-01",
    address: "321 Elm St, Houston, TX 77001",
    emergencyContact: "+1 (555) 0904",
    notes: "Knee replacement surgery completed. Follow-up not required.",
  },
  {
    id: "PAT-005",
    patientId: "P-2024-0005",
    name: "Amanda Taylor",
    initials: "AT",
    avatar: "",
    age: 29,
    gender: "Female",
    bloodGroup: "O+",
    email: "amanda.taylor@email.com",
    phone: "+1 (555) 0105",
    department: "Dermatology",
    assignedDoctor: "Dr. Michael Torres",
    assignedDoctorInitials: "MT",
    lastVisit: "2026-01-08",
    upcomingAppointment: "2026-02-15",
    status: "Active",
    insurance: "Blue Cross",
    registrationDate: "2024-08-12",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    emergencyContact: "+1 (555) 0905",
    notes: "Acne treatment ongoing. Showing improvement with current regimen.",
  },
  {
    id: "PAT-006",
    patientId: "P-2024-0006",
    name: "William Davis",
    initials: "WD",
    avatar: "",
    age: 72,
    gender: "Male",
    bloodGroup: "A-",
    email: "william.davis@email.com",
    phone: "+1 (555) 0106",
    department: "Cardiology",
    assignedDoctor: "Dr. Emily Watson",
    assignedDoctorInitials: "EW",
    lastVisit: "2026-01-12",
    upcomingAppointment: "2026-01-28",
    status: "Admitted",
    insurance: "Medicare",
    registrationDate: "2024-04-05",
    address: "987 Cedar Ln, Philadelphia, PA 19101",
    emergencyContact: "+1 (555) 0906",
    notes: "Admitted for cardiac monitoring. Scheduled for angioplasty.",
  },
  {
    id: "PAT-007",
    patientId: "P-2024-0007",
    name: "Olivia Brown",
    initials: "OB",
    avatar: "",
    age: 31,
    gender: "Female",
    bloodGroup: "B-",
    email: "olivia.brown@email.com",
    phone: "+1 (555) 0107",
    department: "Neurology",
    assignedDoctor: "Dr. Robert Chen",
    assignedDoctorInitials: "RC",
    lastVisit: "2025-11-20",
    upcomingAppointment: null,
    status: "Inactive",
    insurance: "Cigna",
    registrationDate: "2024-09-01",
    address: "234 Birch St, San Antonio, TX 78201",
    emergencyContact: "+1 (555) 0907",
    notes: "Patient moved out of state. Records transferred.",
  },
  {
    id: "PAT-008",
    patientId: "P-2024-0008",
    name: "Daniel Kim",
    initials: "DK",
    avatar: "",
    age: 19,
    gender: "Male",
    bloodGroup: "AB-",
    email: "daniel.kim@email.com",
    phone: "+1 (555) 0108",
    department: "Orthopedics",
    assignedDoctor: "Dr. William Taylor",
    assignedDoctorInitials: "WT",
    lastVisit: "2026-01-02",
    upcomingAppointment: "2026-01-30",
    status: "Active",
    insurance: "Aetna",
    registrationDate: "2024-11-15",
    address: "567 Walnut Ave, San Diego, CA 92101",
    emergencyContact: "+1 (555) 0908",
    notes: "Sports injury recovery. Physical therapy progress is good.",
  },
  {
    id: "PAT-009",
    patientId: "P-2024-0009",
    name: "Isabella Garcia",
    initials: "IG",
    avatar: "",
    age: 52,
    gender: "Female",
    bloodGroup: "A+",
    email: "isabella.garcia@email.com",
    phone: "+1 (555) 0109",
    department: "Dermatology",
    assignedDoctor: "Dr. Olivia Brown",
    assignedDoctorInitials: "OB",
    lastVisit: "2025-12-10",
    upcomingAppointment: null,
    status: "Discharged",
    insurance: "United Health",
    registrationDate: "2024-05-20",
    address: "890 Spruce Ct, Dallas, TX 75201",
    emergencyContact: "+1 (555) 0909",
    notes: "Skin cancer screening completed. All clear.",
  },
  {
    id: "PAT-010",
    patientId: "P-2024-0010",
    name: "Alexander Wright",
    initials: "AW",
    avatar: "",
    age: 41,
    gender: "Male",
    bloodGroup: "O+",
    email: "alexander.wright@email.com",
    phone: "+1 (555) 0110",
    department: "Cardiology",
    assignedDoctor: "Dr. Sarah Johnson",
    assignedDoctorInitials: "SJ",
    lastVisit: "2026-01-14",
    upcomingAppointment: "2026-02-10",
    status: "Active",
    insurance: "Blue Cross",
    registrationDate: "2024-07-08",
    address: "432 Ash Blvd, San Jose, CA 95101",
    emergencyContact: "+1 (555) 0910",
    notes: "Post-heart attack recovery. Lifestyle changes recommended.",
  },
  {
    id: "PAT-011",
    patientId: "P-2024-0011",
    name: "Mia Thompson",
    initials: "MT",
    avatar: "",
    age: 3,
    gender: "Female",
    bloodGroup: "B+",
    email: "mia.thompson@email.com",
    phone: "+1 (555) 0111",
    department: "Pediatrics",
    assignedDoctor: "Dr. Anna Martinez",
    assignedDoctorInitials: "AM",
    lastVisit: "2026-01-11",
    upcomingAppointment: "2026-02-05",
    status: "Active",
    insurance: "Cigna",
    registrationDate: "2025-01-10",
    address: "159 Cherry Ln, Austin, TX 73301",
    emergencyContact: "+1 (555) 0911",
    notes: "Routine vaccination and development check-up.",
  },
  {
    id: "PAT-012",
    patientId: "P-2024-0012",
    name: "Ethan Moore",
    initials: "EM",
    avatar: "",
    age: 63,
    gender: "Male",
    bloodGroup: "A+",
    email: "ethan.moore@email.com",
    phone: "+1 (555) 0112",
    department: "Neurology",
    assignedDoctor: "Dr. James Mitchell",
    assignedDoctorInitials: "JM",
    lastVisit: "2026-01-07",
    upcomingAppointment: null,
    status: "Pending",
    insurance: "Medicare",
    registrationDate: "2025-02-14",
    address: "753 Fir Way, Denver, CO 80201",
    emergencyContact: "+1 (555) 0912",
    notes: "Awaiting MRI results for suspected Parkinson's symptoms.",
  },
  {
    id: "PAT-013",
    patientId: "P-2024-0013",
    name: "Charlotte Lee",
    initials: "CL",
    avatar: "",
    age: 27,
    gender: "Female",
    bloodGroup: "O-",
    email: "charlotte.lee@email.com",
    phone: "+1 (555) 0113",
    department: "Orthopedics",
    assignedDoctor: "Dr. David Kim",
    assignedDoctorInitials: "DK",
    lastVisit: "2025-12-22",
    upcomingAppointment: "2026-01-22",
    status: "Active",
    insurance: "Aetna",
    registrationDate: "2024-10-01",
    address: "321 Willow Dr, Seattle, WA 98101",
    emergencyContact: "+1 (555) 0913",
    notes: "Fractured wrist follow-up. Cast removal scheduled.",
  },
  {
    id: "PAT-014",
    patientId: "P-2024-0014",
    name: "Benjamin Hall",
    initials: "BH",
    avatar: "",
    age: 48,
    gender: "Male",
    bloodGroup: "AB+",
    email: "benjamin.hall@email.com",
    phone: "+1 (555) 0114",
    department: "Cardiology",
    assignedDoctor: "Dr. Christopher Lee",
    assignedDoctorInitials: "CL",
    lastVisit: "2026-01-13",
    upcomingAppointment: "2026-02-20",
    status: "Admitted",
    insurance: "United Health",
    registrationDate: "2024-03-22",
    address: "654 Poplar Ave, Boston, MA 02101",
    emergencyContact: "+1 (555) 0914",
    notes: "Chest pain evaluation. Scheduled for stress test.",
  },
  {
    id: "PAT-015",
    patientId: "P-2024-0015",
    name: "Amelia Clark",
    initials: "AC",
    avatar: "",
    age: 25,
    gender: "Female",
    bloodGroup: "A-",
    email: "amelia.clark@email.com",
    phone: "+1 (555) 0115",
    department: "Dermatology",
    assignedDoctor: "Dr. Michael Torres",
    assignedDoctorInitials: "MT",
    lastVisit: "2026-01-09",
    upcomingAppointment: "2026-02-12",
    status: "Pending",
    insurance: "Blue Cross",
    registrationDate: "2025-03-05",
    address: "852 Laurel St, Miami, FL 33101",
    emergencyContact: "+1 (555) 0915",
    notes: "First visit. Referred for eczema treatment.",
  },
  {
    id: "PAT-016",
    patientId: "P-2024-0016",
    name: "Lucas Turner",
    initials: "LT",
    avatar: "",
    age: 55,
    gender: "Male",
    bloodGroup: "B+",
    email: "lucas.turner@email.com",
    phone: "+1 (555) 0116",
    department: "Neurology",
    assignedDoctor: "Dr. Sophia Williams",
    assignedDoctorInitials: "SW",
    lastVisit: "2025-10-30",
    upcomingAppointment: null,
    status: "Inactive",
    insurance: "Aetna",
    registrationDate: "2024-04-18",
    address: "147 Hickory Ln, Portland, OR 97201",
    emergencyContact: "+1 (555) 0916",
    notes: "Patient discontinued treatment. Records on hold.",
  },
  {
    id: "PAT-017",
    patientId: "P-2024-0017",
    name: "Harper White",
    initials: "HW",
    avatar: "",
    age: 38,
    gender: "Female",
    bloodGroup: "AB-",
    email: "harper.white@email.com",
    phone: "+1 (555) 0117",
    department: "Pediatrics",
    assignedDoctor: "Dr. Lisa Park",
    assignedDoctorInitials: "LP",
    lastVisit: "2026-01-06",
    upcomingAppointment: "2026-01-27",
    status: "Active",
    insurance: "Cigna",
    registrationDate: "2024-12-01",
    address: "963 Magnolia Ct, Atlanta, GA 30301",
    emergencyContact: "+1 (555) 0917",
    notes: "Parent bringing child for routine pediatric consultation.",
  },
  {
    id: "PAT-018",
    patientId: "P-2024-0018",
    name: "Henry Adams",
    initials: "HA",
    avatar: "",
    age: 67,
    gender: "Male",
    bloodGroup: "O+",
    email: "henry.adams@email.com",
    phone: "+1 (555) 0118",
    department: "Orthopedics",
    assignedDoctor: "Dr. William Taylor",
    assignedDoctorInitials: "WT",
    lastVisit: "2025-12-05",
    upcomingAppointment: null,
    status: "Discharged",
    insurance: "Medicare",
    registrationDate: "2024-05-30",
    address: "258 Sycamore Dr, Minneapolis, MN 55401",
    emergencyContact: "+1 (555) 0918",
    notes: "Hip replacement surgery successful. Recovery at home.",
  },
  {
    id: "PAT-019",
    patientId: "P-2024-0019",
    name: "Evelyn Scott",
    initials: "ES",
    avatar: "",
    age: 22,
    gender: "Female",
    bloodGroup: "A+",
    email: "evelyn.scott@email.com",
    phone: "+1 (555) 0119",
    department: "Dermatology",
    assignedDoctor: "Dr. Olivia Brown",
    assignedDoctorInitials: "OB",
    lastVisit: "2026-01-04",
    upcomingAppointment: "2026-02-08",
    status: "Active",
    insurance: "Blue Cross",
    registrationDate: "2024-11-28",
    address: "741 Aspen Rd, Charlotte, NC 28201",
    emergencyContact: "+1 (555) 0919",
    notes: "Rosacea treatment. Prescribed topical cream.",
  },
  {
    id: "PAT-020",
    patientId: "P-2024-0020",
    name: "Jackson Hill",
    initials: "JH",
    avatar: "",
    age: 15,
    gender: "Male",
    bloodGroup: "B-",
    email: "jackson.hill@email.com",
    phone: "+1 (555) 0120",
    department: "Pediatrics",
    assignedDoctor: "Dr. Anna Martinez",
    assignedDoctorInitials: "AM",
    lastVisit: "2026-01-03",
    upcomingAppointment: null,
    status: "Pending",
    insurance: "Aetna",
    registrationDate: "2025-04-14",
    address: "369 Redwood Ave, Nashville, TN 37201",
    emergencyContact: "+1 (555) 0920",
    notes: "Growth assessment requested by school. Appointments pending.",
  },
  {
    id: "PAT-021",
    patientId: "P-2024-0021",
    name: "Aria Martinez",
    initials: "AM",
    avatar: "",
    age: 40,
    gender: "Female",
    bloodGroup: "O+",
    email: "aria.martinez@email.com",
    phone: "+1 (555) 0121",
    department: "Cardiology",
    assignedDoctor: "Dr. Sarah Johnson",
    assignedDoctorInitials: "SJ",
    lastVisit: "2026-01-15",
    upcomingAppointment: "2026-02-18",
    status: "Active",
    insurance: "United Health",
    registrationDate: "2024-08-25",
    address: "582 Beech St, Detroit, MI 48201",
    emergencyContact: "+1 (555) 0921",
    notes: "Routine cardiac check-up. Family history of heart disease.",
  },
  {
    id: "PAT-022",
    patientId: "P-2024-0022",
    name: "Logan Baker",
    initials: "LB",
    avatar: "",
    age: 50,
    gender: "Male",
    bloodGroup: "A+",
    email: "logan.baker@email.com",
    phone: "+1 (555) 0122",
    department: "Neurology",
    assignedDoctor: "Dr. Robert Chen",
    assignedDoctorInitials: "RC",
    lastVisit: "2025-11-15",
    upcomingAppointment: null,
    status: "Inactive",
    insurance: "Cigna",
    registrationDate: "2024-09-14",
    address: "194 Cypress Way, Baltimore, MD 21201",
    emergencyContact: "+1 (555) 0922",
    notes: "Tinnitus treatment discontinued. No follow-up needed.",
  },
  {
    id: "PAT-023",
    patientId: "P-2024-0023",
    name: "Scarlett Nelson",
    initials: "SN",
    avatar: "",
    age: 60,
    gender: "Female",
    bloodGroup: "AB+",
    email: "scarlett.nelson@email.com",
    phone: "+1 (555) 0123",
    department: "Orthopedics",
    assignedDoctor: "Dr. David Kim",
    assignedDoctorInitials: "DK",
    lastVisit: "2026-01-10",
    upcomingAppointment: "2026-02-03",
    status: "Active",
    insurance: "Medicare",
    registrationDate: "2024-07-07",
    address: "706 Dogwood Ln, St. Louis, MO 63101",
    emergencyContact: "+1 (555) 0923",
    notes: "Osteoarthritis management. Joint injections scheduled.",
  },
  {
    id: "PAT-024",
    patientId: "P-2024-0024",
    name: "Samuel Carter",
    initials: "SC",
    avatar: "",
    age: 33,
    gender: "Male",
    bloodGroup: "O-",
    email: "samuel.carter@email.com",
    phone: "+1 (555) 0124",
    department: "Cardiology",
    assignedDoctor: "Dr. Christopher Lee",
    assignedDoctorInitials: "CL",
    lastVisit: "2025-12-30",
    upcomingAppointment: null,
    status: "Discharged",
    insurance: "Blue Cross",
    registrationDate: "2024-06-12",
    address: "821 Spruce Ct, Pittsburgh, PA 15201",
    emergencyContact: "+1 (555) 0924",
    notes: "Arrhythmia resolved. No further treatment required.",
  },
  {
    id: "PAT-025",
    patientId: "P-2024-0025",
    name: "Grace Mitchell",
    initials: "GM",
    avatar: "",
    age: 17,
    gender: "Female",
    bloodGroup: "B+",
    email: "grace.mitchell@email.com",
    phone: "+1 (555) 0125",
    department: "Dermatology",
    assignedDoctor: "Dr. Michael Torres",
    assignedDoctorInitials: "MT",
    lastVisit: "2026-01-12",
    upcomingAppointment: "2026-02-19",
    status: "Active",
    insurance: "Aetna",
    registrationDate: "2024-10-20",
    address: "435 Poplar St, Tampa, FL 33601",
    emergencyContact: "+1 (555) 0925",
    notes: "Teen acne consultation. Started new treatment plan.",
  },
];

export const departmentOptions = [
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Dermatology",
];

export const doctorOptions = [
  "Dr. Sarah Johnson",
  "Dr. James Mitchell",
  "Dr. Lisa Park",
  "Dr. David Kim",
  "Dr. Michael Torres",
  "Dr. Emily Watson",
  "Dr. Robert Chen",
  "Dr. Anna Martinez",
  "Dr. William Taylor",
  "Dr. Olivia Brown",
  "Dr. Christopher Lee",
  "Dr. Sophia Williams",
];

export const bloodGroupOptions: BloodGroup[] = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
];

export const genderOptions = ["Male", "Female"] as const;

export const insuranceOptions = [
  "Blue Cross",
  "Aetna",
  "Cigna",
  "United Health",
  "Medicare",
  "None",
];

export const statusOptions: PatientStatus[] = [
  "Active",
  "Inactive",
  "Admitted",
  "Discharged",
  "Pending",
];

export const ageRanges = [
  { label: "0-12 years", min: 0, max: 12 },
  { label: "13-17 years", min: 13, max: 17 },
  { label: "18-30 years", min: 18, max: 30 },
  { label: "31-45 years", min: 31, max: 45 },
  { label: "46-60 years", min: 46, max: 60 },
  { label: "60+ years", min: 61, max: 120 },
];
