import type {
  Appointment,
  AppointmentStatus,
  ConsultationType,
  PaymentStatus,
} from "./types";

export const appointmentsData: Appointment[] = [
  {
    id: "APT-001",
    appointmentId: "A-2026-0001",
    patientName: "Emily Johnson",
    patientInitials: "EJ",
    patientAvatar: "",
    patientAge: 34,
    patientGender: "Female",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-12",
    time: "09:00",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Regular cardiac checkup",
    createdAt: "2026-06-28",
  },
  {
    id: "APT-002",
    appointmentId: "A-2026-0002",
    patientName: "James Wilson",
    patientInitials: "JW",
    patientAvatar: "",
    patientAge: 58,
    patientGender: "Male",
    doctorName: "Dr. James Mitchell",
    doctorInitials: "JM",
    department: "Neurology",
    date: "2026-07-12",
    time: "09:30",
    duration: 45,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Checked In",
    notes: "Migraine follow-up",
    createdAt: "2026-06-25",
  },
  {
    id: "APT-003",
    appointmentId: "A-2026-0003",
    patientName: "Sophia Martinez",
    patientInitials: "SM",
    patientAvatar: "",
    patientAge: 28,
    patientGender: "Female",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-12",
    time: "10:00",
    duration: 30,
    consultationType: "Video",
    paymentStatus: "Paid",
    status: "In Progress",
    notes: "Child vaccination",
    createdAt: "2026-06-30",
  },
  {
    id: "APT-004",
    appointmentId: "A-2026-0004",
    patientName: "William Davis",
    patientInitials: "WD",
    patientAvatar: "",
    patientAge: 45,
    patientGender: "Male",
    doctorName: "Dr. Robert Kim",
    doctorInitials: "RK",
    department: "Orthopedics",
    date: "2026-07-12",
    time: "10:30",
    duration: 60,
    consultationType: "In-Person",
    paymentStatus: "Pending",
    status: "Pending",
    notes: "Knee pain evaluation",
    createdAt: "2026-07-01",
  },
  {
    id: "APT-005",
    appointmentId: "A-2026-0005",
    patientName: "Olivia Brown",
    patientInitials: "OB",
    patientAvatar: "",
    patientAge: 52,
    patientGender: "Female",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-12",
    time: "11:00",
    duration: 30,
    consultationType: "Phone",
    paymentStatus: "Waived",
    status: "Completed",
    notes: "Blood pressure review",
    createdAt: "2026-06-20",
  },
  {
    id: "APT-006",
    appointmentId: "A-2026-0006",
    patientName: "Liam Anderson",
    patientInitials: "LA",
    patientAvatar: "",
    patientAge: 19,
    patientGender: "Male",
    doctorName: "Dr. Michael Torres",
    doctorInitials: "MT",
    department: "Dermatology",
    date: "2026-07-12",
    time: "11:30",
    duration: 20,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Cancelled",
    notes: "Acne treatment - cancelled by patient",
    createdAt: "2026-07-02",
  },
  {
    id: "APT-007",
    appointmentId: "A-2026-0007",
    patientName: "Emma Taylor",
    patientInitials: "ET",
    patientAvatar: "",
    patientAge: 41,
    patientGender: "Female",
    doctorName: "Dr. James Mitchell",
    doctorInitials: "JM",
    department: "Neurology",
    date: "2026-07-12",
    time: "13:00",
    duration: 45,
    consultationType: "Video",
    paymentStatus: "Insurance",
    status: "Confirmed",
    notes: "Neurological assessment",
    createdAt: "2026-07-05",
  },
  {
    id: "APT-008",
    appointmentId: "A-2026-0008",
    patientName: "Noah Thomas",
    patientInitials: "NT",
    patientAvatar: "",
    patientAge: 63,
    patientGender: "Male",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-12",
    time: "14:00",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Pending",
    status: "No Show",
    notes: "Pediatric consultation - patient did not arrive",
    createdAt: "2026-07-03",
  },
  {
    id: "APT-009",
    appointmentId: "A-2026-0009",
    patientName: "Ava Jackson",
    patientInitials: "AJ",
    patientAvatar: "",
    patientAge: 37,
    patientGender: "Female",
    doctorName: "Dr. Robert Kim",
    doctorInitials: "RK",
    department: "Orthopedics",
    date: "2026-07-12",
    time: "14:30",
    duration: 45,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Rescheduled",
    notes: "Rescheduled from July 10th",
    createdAt: "2026-07-04",
  },
  {
    id: "APT-010",
    appointmentId: "A-2026-0010",
    patientName: "Ethan Garcia",
    patientInitials: "EG",
    patientAvatar: "",
    patientAge: 55,
    patientGender: "Male",
    doctorName: "Dr. Michael Torres",
    doctorInitials: "MT",
    department: "Dermatology",
    date: "2026-07-13",
    time: "09:00",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Confirmed",
    notes: "Skin screening",
    createdAt: "2026-07-06",
  },
  {
    id: "APT-011",
    appointmentId: "A-2026-0011",
    patientName: "Isabella White",
    patientInitials: "IW",
    patientAvatar: "",
    patientAge: 31,
    patientGender: "Female",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-13",
    time: "10:00",
    duration: 30,
    consultationType: "Phone",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Post-op checkup",
    createdAt: "2026-07-07",
  },
  {
    id: "APT-012",
    appointmentId: "A-2026-0012",
    patientName: "Mason Lee",
    patientInitials: "ML",
    patientAvatar: "",
    patientAge: 8,
    patientGender: "Male",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-13",
    time: "11:00",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Pending",
    status: "Pending",
    notes: "School physical examination",
    createdAt: "2026-07-08",
  },
  {
    id: "APT-013",
    appointmentId: "A-2026-0013",
    patientName: "Mia Harris",
    patientInitials: "MH",
    patientAvatar: "",
    patientAge: 47,
    patientGender: "Female",
    doctorName: "Dr. James Mitchell",
    doctorInitials: "JM",
    department: "Neurology",
    date: "2026-07-13",
    time: "13:00",
    duration: 60,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Checked In",
    notes: "MRI results discussion",
    createdAt: "2026-07-02",
  },
  {
    id: "APT-014",
    appointmentId: "A-2026-0014",
    patientName: "Lucas Martin",
    patientInitials: "LM",
    patientAvatar: "",
    patientAge: 29,
    patientGender: "Male",
    doctorName: "Dr. Robert Kim",
    doctorInitials: "RK",
    department: "Orthopedics",
    date: "2026-07-14",
    time: "09:00",
    duration: 30,
    consultationType: "Video",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Fracture follow-up",
    createdAt: "2026-07-09",
  },
  {
    id: "APT-015",
    appointmentId: "A-2026-0015",
    patientName: "Charlotte Clark",
    patientInitials: "CC",
    patientAvatar: "",
    patientAge: 72,
    patientGender: "Female",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-14",
    time: "10:00",
    duration: 45,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Confirmed",
    notes: "Heart rhythm monitoring",
    createdAt: "2026-07-10",
  },
  {
    id: "APT-016",
    appointmentId: "A-2026-0016",
    patientName: "Alexander Lewis",
    patientInitials: "AL",
    patientAvatar: "",
    patientAge: 25,
    patientGender: "Male",
    doctorName: "Dr. Michael Torres",
    doctorInitials: "MT",
    department: "Dermatology",
    date: "2026-07-14",
    time: "11:00",
    duration: 20,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Pending",
    notes: "Mole check",
    createdAt: "2026-07-11",
  },
  {
    id: "APT-017",
    appointmentId: "A-2026-0017",
    patientName: "Amelia Walker",
    patientInitials: "AW",
    patientAvatar: "",
    patientAge: 39,
    patientGender: "Female",
    doctorName: "Dr. James Mitchell",
    doctorInitials: "JM",
    department: "Neurology",
    date: "2026-07-12",
    time: "15:00",
    duration: 45,
    consultationType: "Emergency",
    paymentStatus: "Insurance",
    status: "In Progress",
    notes: "Emergency consultation - severe headache",
    createdAt: "2026-07-12",
  },
  {
    id: "APT-018",
    appointmentId: "A-2026-0018",
    patientName: "Benjamin Hall",
    patientInitials: "BH",
    patientAvatar: "",
    patientAge: 22,
    patientGender: "Male",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-15",
    time: "09:30",
    duration: 30,
    consultationType: "Phone",
    paymentStatus: "Pending",
    status: "Pending",
    notes: "Allergy consultation",
    createdAt: "2026-07-12",
  },
  {
    id: "APT-019",
    appointmentId: "A-2026-0019",
    patientName: "Harper Young",
    patientInitials: "HY",
    patientAvatar: "",
    patientAge: 67,
    patientGender: "Female",
    doctorName: "Dr. Robert Kim",
    doctorInitials: "RK",
    department: "Orthopedics",
    date: "2026-07-15",
    time: "14:00",
    duration: 45,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Completed",
    notes: "Hip replacement follow-up",
    createdAt: "2026-07-08",
  },
  {
    id: "APT-020",
    appointmentId: "A-2026-0020",
    patientName: "Daniel King",
    patientInitials: "DK",
    patientAvatar: "",
    patientAge: 51,
    patientGender: "Male",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-15",
    time: "15:00",
    duration: 30,
    consultationType: "Video",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Annual cardiac evaluation",
    createdAt: "2026-07-10",
  },
  {
    id: "APT-021",
    appointmentId: "A-2026-0021",
    patientName: "Evelyn Wright",
    patientInitials: "EW",
    patientAvatar: "",
    patientAge: 33,
    patientGender: "Female",
    doctorName: "Dr. Michael Torres",
    doctorInitials: "MT",
    department: "Dermatology",
    date: "2026-07-16",
    time: "10:00",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Confirmed",
    notes: "Skin rash evaluation",
    createdAt: "2026-07-11",
  },
  {
    id: "APT-022",
    appointmentId: "A-2026-0022",
    patientName: "James Wilson",
    patientInitials: "JW",
    patientAvatar: "",
    patientAge: 58,
    patientGender: "Male",
    doctorName: "Dr. James Mitchell",
    doctorInitials: "JM",
    department: "Neurology",
    date: "2026-07-12",
    time: "08:30",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Completed",
    notes: "Early morning follow-up",
    createdAt: "2026-07-05",
  },
  {
    id: "APT-023",
    appointmentId: "A-2026-0023",
    patientName: "Abigail Scott",
    patientInitials: "AS",
    patientAvatar: "",
    patientAge: 44,
    patientGender: "Female",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-16",
    time: "14:00",
    duration: 30,
    consultationType: "Video",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Developmental screening",
    createdAt: "2026-07-12",
  },
  {
    id: "APT-024",
    appointmentId: "A-2026-0024",
    patientName: "Elijah Green",
    patientInitials: "EG",
    patientAvatar: "",
    patientAge: 16,
    patientGender: "Male",
    doctorName: "Dr. Robert Kim",
    doctorInitials: "RK",
    department: "Orthopedics",
    date: "2026-07-17",
    time: "11:00",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Pending",
    status: "Pending",
    notes: "Sports injury assessment",
    createdAt: "2026-07-13",
  },
  {
    id: "APT-025",
    appointmentId: "A-2026-0025",
    patientName: "Emily Johnson",
    patientInitials: "EJ",
    patientAvatar: "",
    patientAge: 34,
    patientGender: "Female",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-12",
    time: "16:00",
    duration: 30,
    consultationType: "Phone",
    paymentStatus: "Paid",
    status: "Cancelled",
    notes: "Rescheduled to next week",
    createdAt: "2026-07-06",
  },
  {
    id: "APT-026",
    appointmentId: "A-2026-0026",
    patientName: "Sofia Rodriguez",
    patientInitials: "SR",
    patientAvatar: "",
    patientAge: 9,
    patientGender: "Female",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-13",
    time: "15:30",
    duration: 30,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "No Show",
    notes: "Routine checkup - no show",
    createdAt: "2026-07-07",
  },
  {
    id: "APT-027",
    appointmentId: "A-2026-0027",
    patientName: "Henry Baker",
    patientInitials: "HB",
    patientAvatar: "",
    patientAge: 61,
    patientGender: "Male",
    doctorName: "Dr. Michael Torres",
    doctorInitials: "MT",
    department: "Dermatology",
    date: "2026-07-17",
    time: "14:30",
    duration: 45,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Confirmed",
    notes: "Full body skin exam",
    createdAt: "2026-07-14",
  },
  {
    id: "APT-028",
    appointmentId: "A-2026-0028",
    patientName: "Victoria Adams",
    patientInitials: "VA",
    patientAvatar: "",
    patientAge: 50,
    patientGender: "Female",
    doctorName: "Dr. James Mitchell",
    doctorInitials: "JM",
    department: "Neurology",
    date: "2026-07-18",
    time: "09:00",
    duration: 60,
    consultationType: "In-Person",
    paymentStatus: "Pending",
    status: "Pending",
    notes: "Sleep study consultation",
    createdAt: "2026-07-15",
  },
  {
    id: "APT-029",
    appointmentId: "A-2026-0029",
    patientName: "Sebastian Nelson",
    patientInitials: "SN",
    patientAvatar: "",
    patientAge: 27,
    patientGender: "Male",
    doctorName: "Dr. Sarah Johnson",
    doctorInitials: "SJ",
    department: "Cardiology",
    date: "2026-07-18",
    time: "11:00",
    duration: 30,
    consultationType: "Video",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Exercise stress test results",
    createdAt: "2026-07-16",
  },
  {
    id: "APT-030",
    appointmentId: "A-2026-0030",
    patientName: "Grace Mitchell",
    patientInitials: "GM",
    patientAvatar: "",
    patientAge: 5,
    patientGender: "Female",
    doctorName: "Dr. Emily Chen",
    doctorInitials: "EC",
    department: "Pediatrics",
    date: "2026-07-19",
    time: "10:00",
    duration: 20,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Pending",
    notes: "Vaccination appointment",
    createdAt: "2026-07-17",
  },
  {
    id: "APT-031",
    appointmentId: "A-2026-0031",
    patientName: "Samuel Carter",
    patientInitials: "SC",
    patientAvatar: "",
    patientAge: 70,
    patientGender: "Male",
    doctorName: "Dr. Robert Kim",
    doctorInitials: "RK",
    department: "Orthopedics",
    date: "2026-07-12",
    time: "07:30",
    duration: 60,
    consultationType: "In-Person",
    paymentStatus: "Insurance",
    status: "Completed",
    notes: "Pre-surgery assessment",
    createdAt: "2026-07-01",
  },
  {
    id: "APT-032",
    appointmentId: "A-2026-0032",
    patientName: "Chloe Turner",
    patientInitials: "CT",
    patientAvatar: "",
    patientAge: 16,
    patientGender: "Female",
    doctorName: "Dr. Michael Torres",
    doctorInitials: "MT",
    department: "Dermatology",
    date: "2026-07-19",
    time: "14:00",
    duration: 20,
    consultationType: "In-Person",
    paymentStatus: "Paid",
    status: "Confirmed",
    notes: "Teen acne follow-up",
    createdAt: "2026-07-17",
  },
];

export const departmentOptions = [
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Dermatology",
] as const;

export const doctorOptions = [
  "Dr. Sarah Johnson",
  "Dr. James Mitchell",
  "Dr. Emily Chen",
  "Dr. Robert Kim",
  "Dr. Michael Torres",
] as const;

export const statusOptions: readonly AppointmentStatus[] = [
  "Confirmed",
  "Pending",
  "Completed",
  "Cancelled",
  "No Show",
  "Rescheduled",
  "Checked In",
  "In Progress",
];

export const consultationTypeOptions: readonly ConsultationType[] = [
  "Video",
  "In-Person",
  "Phone",
  "Emergency",
];

export const paymentStatusOptions: readonly PaymentStatus[] = [
  "Paid",
  "Pending",
  "Refunded",
  "Waived",
  "Insurance",
];

export const quickStatusOptions: readonly AppointmentStatus[] = [
  "Confirmed",
  "Pending",
  "Completed",
  "Cancelled",
  "No Show",
  "Checked In",
];
