import type { Doctor } from "./types";

export const doctorsData: Doctor[] = [
  {
    id: "DOC-001",
    name: "Dr. Sarah Johnson",
    initials: "SJ",
    photo: "",
    department: "Cardiology",
    specialization: "Interventional Cardiology",
    experience: 14,
    patients: 245,
    rating: 4.9,
    status: "Active",
    availability: "Available",
    gender: "Female",
    languages: ["English", "Spanish"],
    consultationType: "Both",
    email: "sarah.johnson@mediflow.com",
    phone: "+1 (555) 0101",
    appointmentsToday: 6,
    verified: true,
  },
  {
    id: "DOC-002",
    name: "Dr. James Mitchell",
    initials: "JM",
    photo: "",
    department: "Neurology",
    specialization: "Clinical Neurophysiology",
    experience: 18,
    patients: 198,
    rating: 4.8,
    status: "Active",
    availability: "Busy",
    gender: "Male",
    languages: ["English"],
    consultationType: "Offline",
    email: "james.mitchell@mediflow.com",
    phone: "+1 (555) 0102",
    appointmentsToday: 8,
    verified: true,
  },
  {
    id: "DOC-003",
    name: "Dr. Lisa Park",
    initials: "LP",
    photo: "",
    department: "Pediatrics",
    specialization: "Neonatology",
    experience: 11,
    patients: 267,
    rating: 4.9,
    status: "Active",
    availability: "Available",
    gender: "Female",
    languages: ["English", "Korean", "Mandarin"],
    consultationType: "Both",
    email: "lisa.park@mediflow.com",
    phone: "+1 (555) 0103",
    appointmentsToday: 5,
    verified: true,
  },
  {
    id: "DOC-004",
    name: "Dr. David Kim",
    initials: "DK",
    photo: "",
    department: "Orthopedics",
    specialization: "Sports Medicine",
    experience: 15,
    patients: 178,
    rating: 4.7,
    status: "On Leave",
    availability: "Out of Office",
    gender: "Male",
    languages: ["English", "Korean"],
    consultationType: "Offline",
    email: "david.kim@mediflow.com",
    phone: "+1 (555) 0104",
    appointmentsToday: 0,
    verified: true,
  },
  {
    id: "DOC-005",
    name: "Dr. Michael Torres",
    initials: "MT",
    photo: "",
    department: "Dermatology",
    specialization: "Cosmetic Dermatology",
    experience: 9,
    patients: 156,
    rating: 4.8,
    status: "Active",
    availability: "Available",
    gender: "Male",
    languages: ["English", "Spanish", "Portuguese"],
    consultationType: "Both",
    email: "michael.torres@mediflow.com",
    phone: "+1 (555) 0105",
    appointmentsToday: 4,
    verified: true,
  },
  {
    id: "DOC-006",
    name: "Dr. Emily Watson",
    initials: "EW",
    photo: "",
    department: "Cardiology",
    specialization: "Electrophysiology",
    experience: 7,
    patients: 132,
    rating: 4.6,
    status: "Active",
    availability: "Busy",
    gender: "Female",
    languages: ["English", "French"],
    consultationType: "Both",
    email: "emily.watson@mediflow.com",
    phone: "+1 (555) 0106",
    appointmentsToday: 7,
    verified: false,
  },
  {
    id: "DOC-007",
    name: "Dr. Robert Chen",
    initials: "RC",
    photo: "",
    department: "Neurology",
    specialization: "Stroke Medicine",
    experience: 22,
    patients: 310,
    rating: 4.9,
    status: "Active",
    availability: "Available",
    gender: "Male",
    languages: ["English", "Mandarin", "Cantonese"],
    consultationType: "Both",
    email: "robert.chen@mediflow.com",
    phone: "+1 (555) 0107",
    appointmentsToday: 3,
    verified: true,
  },
  {
    id: "DOC-008",
    name: "Dr. Anna Martinez",
    initials: "AM",
    photo: "",
    department: "Pediatrics",
    specialization: "Pediatric Cardiology",
    experience: 6,
    patients: 98,
    rating: 4.5,
    status: "Vacation",
    availability: "Out of Office",
    gender: "Female",
    languages: ["English", "Spanish"],
    consultationType: "Online",
    email: "anna.martinez@mediflow.com",
    phone: "+1 (555) 0108",
    appointmentsToday: 0,
    verified: false,
  },
  {
    id: "DOC-009",
    name: "Dr. William Taylor",
    initials: "WT",
    photo: "",
    department: "Orthopedics",
    specialization: "Joint Replacement",
    experience: 25,
    patients: 420,
    rating: 4.9,
    status: "Active",
    availability: "Busy",
    gender: "Male",
    languages: ["English", "German"],
    consultationType: "Offline",
    email: "william.taylor@mediflow.com",
    phone: "+1 (555) 0109",
    appointmentsToday: 9,
    verified: true,
  },
  {
    id: "DOC-010",
    name: "Dr. Olivia Brown",
    initials: "OB",
    photo: "",
    department: "Dermatology",
    specialization: "Pediatric Dermatology",
    experience: 5,
    patients: 87,
    rating: 4.4,
    status: "Active",
    availability: "Available",
    gender: "Female",
    languages: ["English"],
    consultationType: "Online",
    email: "olivia.brown@mediflow.com",
    phone: "+1 (555) 0110",
    appointmentsToday: 3,
    verified: false,
  },
  {
    id: "DOC-011",
    name: "Dr. Christopher Lee",
    initials: "CL",
    photo: "",
    department: "Cardiology",
    specialization: "General Cardiology",
    experience: 12,
    patients: 210,
    rating: 4.7,
    status: "Emergency Duty",
    availability: "Busy",
    gender: "Male",
    languages: ["English"],
    consultationType: "Offline",
    email: "christopher.lee@mediflow.com",
    phone: "+1 (555) 0111",
    appointmentsToday: 11,
    verified: true,
  },
  {
    id: "DOC-012",
    name: "Dr. Sophia Williams",
    initials: "SW",
    photo: "",
    department: "Neurology",
    specialization: "Pediatric Neurology",
    experience: 8,
    patients: 145,
    rating: 4.6,
    status: "Inactive",
    availability: "Out of Office",
    gender: "Female",
    languages: ["English", "French"],
    consultationType: "Both",
    email: "sophia.williams@mediflow.com",
    phone: "+1 (555) 0112",
    appointmentsToday: 0,
    verified: false,
  },
];

export const departmentOptions = [
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Dermatology",
];

export const specializationOptions = [
  "Interventional Cardiology",
  "Electrophysiology",
  "General Cardiology",
  "Clinical Neurophysiology",
  "Stroke Medicine",
  "Pediatric Neurology",
  "Neonatology",
  "Pediatric Cardiology",
  "Sports Medicine",
  "Joint Replacement",
  "Cosmetic Dermatology",
  "Pediatric Dermatology",
];

export const languageOptions = [
  "English",
  "Spanish",
  "French",
  "German",
  "Korean",
  "Mandarin",
  "Cantonese",
  "Portuguese",
];

export const experienceRanges = [
  { label: "0-5 years", min: 0, max: 5 },
  { label: "6-10 years", min: 6, max: 10 },
  { label: "11-15 years", min: 11, max: 15 },
  { label: "16-20 years", min: 16, max: 20 },
  { label: "20+ years", min: 21, max: 50 },
];
