export { Departments } from "./departments/Departments";
export { FeaturedDoctors } from "./doctors/FeaturedDoctors";
export { EmergencyBanner } from "./EmergencyBanner";
export { FAQ } from "./FAQ";
export { Footer } from "./footer/Footer";
export { Hero } from "./Hero";
export { HowItWorks } from "./how-it-works/HowItWorks";
export { Navbar } from "./Navbar/Navbar";
export { SpecialtyDoctors } from "./SpecialtyDoctors";
export { StatsBar } from "./Statistics/Statistics";
export { WhyChoose as Features } from "./why-choose/WhyChoose";
