export * from "./AttachmentTab";
export * from "./DiagnosisTab";
export * from "./LabTab";
export * from "./MedicalRecordHero";
export * from "./OverviewTab";
export * from "./PrescriptionTab";
export * from "./QuickSummary";
export * from "./RecordDetails";
export * from "./RecordDetailsSkeleton";
export * from "./RelatedRecords";
export { RelatedRecords } from "./RelatedRecords";
export * from "./TimelineTab";
export { TimelineTab } from "./TimelineTab";
export * from "./TreatmentTab";
export * from "./types";
export * from "./VitalsCard";
