import type { Department } from "./types";

export const departmentsData: Department[] = [
  {
    id: "DEPT-001",
    name: "Cardiology",
    icon: "Heart",
    iconBg: "bg-red-100 dark:bg-red-900/30",
    description:
      "Comprehensive heart care including diagnostics, interventional procedures, and cardiac rehabilitation.",
    head: "Dr. Sarah Johnson",
    headInitials: "SJ",
    doctors: 18,
    patients: 15420,
    appointments: 3420,
    appointmentsToday: 24,
    floor: "3rd Floor",
    building: "Main Building",
    status: "Active",
    createdAt: "2018-03-15",
    satisfaction: 96,
    color: "#dc2626",
  },
  {
    id: "DEPT-002",
    name: "Neurology",
    icon: "Brain",
    iconBg: "bg-violet-100 dark:bg-violet-900/30",
    description:
      "Expert diagnosis and treatment of neurological disorders using advanced diagnostics and therapies.",
    head: "Dr. James Mitchell",
    headInitials: "JM",
    doctors: 14,
    patients: 12450,
    appointments: 2890,
    appointmentsToday: 18,
    floor: "5th Floor",
    building: "Main Building",
    status: "Active",
    createdAt: "2018-05-20",
    satisfaction: 94,
    color: "#7c3aed",
  },
  {
    id: "DEPT-003",
    name: "Pediatrics",
    icon: "Baby",
    iconBg: "bg-sky-100 dark:bg-sky-900/30",
    description:
      "Child-friendly healthcare from infancy through adolescence with compassionate specialized care.",
    head: "Dr. Lisa Park",
    headInitials: "LP",
    doctors: 22,
    patients: 18300,
    appointments: 4100,
    appointmentsToday: 32,
    floor: "2nd Floor",
    building: "Children's Pavilion",
    status: "Active",
    createdAt: "2017-11-01",
    satisfaction: 97,
    color: "#0ea5e9",
  },
  {
    id: "DEPT-004",
    name: "Orthopedics",
    icon: "Bone",
    iconBg: "bg-amber-100 dark:bg-amber-900/30",
    description:
      "Advanced surgical and non-surgical treatments for musculoskeletal conditions and sports injuries.",
    head: "Dr. David Kim",
    headInitials: "DK",
    doctors: 16,
    patients: 11200,
    appointments: 2650,
    appointmentsToday: 15,
    floor: "4th Floor",
    building: "East Wing",
    status: "Active",
    createdAt: "2019-01-10",
    satisfaction: 93,
    color: "#d97706",
  },
  {
    id: "DEPT-005",
    name: "Dermatology",
    icon: "Droplets",
    iconBg: "bg-pink-100 dark:bg-pink-900/30",
    description:
      "Complete skin care services from medical dermatology to cosmetic procedures and laser therapy.",
    head: "Dr. Michael Torres",
    headInitials: "MT",
    doctors: 10,
    patients: 8900,
    appointments: 2100,
    appointmentsToday: 12,
    floor: "6th Floor",
    building: "West Wing",
    status: "Active",
    createdAt: "2019-06-05",
    satisfaction: 91,
    color: "#ec4899",
  },
  {
    id: "DEPT-006",
    name: "Ophthalmology",
    icon: "Eye",
    iconBg: "bg-teal-100 dark:bg-teal-900/30",
    description:
      "Comprehensive eye care including vision correction, cataract surgery, and retinal treatments.",
    head: "Dr. Emily Watson",
    headInitials: "EW",
    doctors: 12,
    patients: 9800,
    appointments: 2340,
    appointmentsToday: 14,
    floor: "7th Floor",
    building: "Main Building",
    status: "Active",
    createdAt: "2018-09-12",
    satisfaction: 95,
    color: "#14b8a6",
  },
  {
    id: "DEPT-007",
    name: "Emergency Medicine",
    icon: "Ambulance",
    iconBg: "bg-orange-100 dark:bg-orange-900/30",
    description:
      "24/7 emergency care for acute medical conditions, trauma, and life-threatening situations.",
    head: "Dr. Robert Chen",
    headInitials: "RC",
    doctors: 35,
    patients: 28500,
    appointments: 8900,
    appointmentsToday: 56,
    floor: "Ground Floor",
    building: "Main Building",
    status: "Active",
    createdAt: "2015-04-01",
    satisfaction: 88,
    color: "#ea580c",
  },
  {
    id: "DEPT-008",
    name: "Psychiatry",
    icon: "HeartPulse",
    iconBg: "bg-indigo-100 dark:bg-indigo-900/30",
    description:
      "Mental health services including therapy, medication management, and specialized treatment programs.",
    head: "Dr. Anna Martinez",
    headInitials: "AM",
    doctors: 9,
    patients: 6700,
    appointments: 1800,
    appointmentsToday: 10,
    floor: "8th Floor",
    building: "North Wing",
    status: "Active",
    createdAt: "2020-02-14",
    satisfaction: 90,
    color: "#6366f1",
  },
  {
    id: "DEPT-009",
    name: "Pulmonology",
    icon: "Lungs",
    iconBg: "bg-cyan-100 dark:bg-cyan-900/30",
    description:
      "Diagnosis and treatment of respiratory conditions with advanced pulmonary function testing.",
    head: "Dr. William Taylor",
    headInitials: "WT",
    doctors: 11,
    patients: 7800,
    appointments: 1950,
    appointmentsToday: 11,
    floor: "4th Floor",
    building: "East Wing",
    status: "Active",
    createdAt: "2019-08-22",
    satisfaction: 92,
    color: "#06b6d4",
  },
  {
    id: "DEPT-010",
    name: "Gynecology",
    icon: "Venus",
    iconBg: "bg-rose-100 dark:bg-rose-900/30",
    description:
      "Comprehensive women's health services from routine exams to advanced reproductive care.",
    head: "Dr. Olivia Brown",
    headInitials: "OB",
    doctors: 13,
    patients: 11200,
    appointments: 2780,
    appointmentsToday: 16,
    floor: "3rd Floor",
    building: "South Wing",
    status: "Active",
    createdAt: "2018-07-18",
    satisfaction: 95,
    color: "#f43f5e",
  },
  {
    id: "DEPT-011",
    name: "ENT",
    icon: "Ear",
    iconBg: "bg-lime-100 dark:bg-lime-900/30",
    description:
      "Ear, nose, and throat care for both pediatric and adult patients with surgical expertise.",
    head: "Dr. Daniel Lee",
    headInitials: "DL",
    doctors: 8,
    patients: 6500,
    appointments: 1650,
    appointmentsToday: 9,
    floor: "5th Floor",
    building: "West Wing",
    status: "Active",
    createdAt: "2019-11-30",
    satisfaction: 93,
    color: "#65a30d",
  },
  {
    id: "DEPT-012",
    name: "Nutrition & Dietetics",
    icon: "Leaf",
    iconBg: "bg-green-100 dark:bg-green-900/30",
    description:
      "Evidence-based nutritional counseling and dietary management for optimal health outcomes.",
    head: "Dr. Maria Garcia",
    headInitials: "MG",
    doctors: 6,
    patients: 4200,
    appointments: 1100,
    appointmentsToday: 7,
    floor: "6th Floor",
    building: "North Wing",
    status: "Active",
    createdAt: "2021-03-08",
    satisfaction: 94,
    color: "#16a34a",
  },
  {
    id: "DEPT-013",
    name: "Radiology",
    icon: "Scan",
    iconBg: "bg-blue-100 dark:bg-blue-900/30",
    description:
      "Advanced diagnostic imaging services including MRI, CT, ultrasound, and X-ray examinations.",
    head: "Dr. John Davis",
    headInitials: "JD",
    doctors: 15,
    patients: 22100,
    appointments: 5600,
    appointmentsToday: 41,
    floor: "1st Floor",
    building: "Main Building",
    status: "Active",
    createdAt: "2016-09-01",
    satisfaction: 89,
    color: "#2563eb",
  },
  {
    id: "DEPT-014",
    name: "Physical Therapy",
    icon: "Activity",
    iconBg: "bg-yellow-100 dark:bg-yellow-900/30",
    description:
      "Rehabilitation services to restore function, reduce pain, and improve mobility after injury or surgery.",
    head: "Dr. Rachel Adams",
    headInitials: "RA",
    doctors: 20,
    patients: 9800,
    appointments: 3200,
    appointmentsToday: 22,
    floor: "1st Floor",
    building: "East Wing",
    status: "Active",
    createdAt: "2017-06-15",
    satisfaction: 96,
    color: "#ca8a04",
  },
  {
    id: "DEPT-015",
    name: "Oncology",
    icon: "Syringe",
    iconBg: "bg-purple-100 dark:bg-purple-900/30",
    description:
      "Comprehensive cancer care with chemotherapy, radiation therapy, and immunotherapy treatments.",
    head: "Dr. Steven Clark",
    headInitials: "SC",
    doctors: 17,
    patients: 8900,
    appointments: 2450,
    appointmentsToday: 19,
    floor: "9th Floor",
    building: "Cardiac Tower",
    status: "Under Maintenance",
    createdAt: "2017-02-10",
    satisfaction: 92,
    color: "#9333ea",
  },
  {
    id: "DEPT-016",
    name: "Nephrology",
    icon: "Droplets",
    iconBg: "bg-slate-100 dark:bg-slate-900/30",
    description:
      "Kidney care including dialysis, transplant evaluation, and management of renal disorders.",
    head: "Dr. Karen White",
    headInitials: "KW",
    doctors: 7,
    patients: 5100,
    appointments: 1350,
    appointmentsToday: 8,
    floor: "4th Floor",
    building: "Main Building",
    status: "Inactive",
    createdAt: "2020-06-20",
    satisfaction: 87,
    color: "#64748b",
  },
];

export const headOptions = [
  ...new Set(departmentsData.map((d) => d.head)),
].sort();

export const buildingOptions = [
  ...new Set(departmentsData.map((d) => d.building)),
].sort();

export const floorOptions = [
  ...new Set(departmentsData.map((d) => d.floor)),
].sort();

export const statusOptions = [...new Set(departmentsData.map((d) => d.status))];
